### PR TITLE
Lookup map reverse lookup functionality

### PR DESCRIPTION
**Pull request by rnd-ash**

### CODE REVIEW

**Comment by chrissivo** [comment]
Hi @rnd-ash ,
I've added some functionality for the Hfm-CAN and would need to merge it to dev. Do you have any concerns?

**Comment by rnd-ash** [comment]
@chrissivo i tried to merge the PR, and noticed a couple issues.

Firstly, `parking_lock_teeth` count in the configuration (EEPROM_CONFIG.H) is already defined in code as `input_sensor_pulses_per_rev`. So I don't think we need this extra configuration option.

Secondly, please remove the files in your .vscode folder from the PR

**Comment by chrissivo** [comment]
Hi  @rnd-ash , Thank you for the hints. Have removed the unneccessary parameter `parking_lock_teeth` and the respective files as well.

**Comment by rnd-ash** [comment]
Merged finally! Thank you @chrissivo for working on this, ill mention it in the changelog

**Pull request merged**
